from __future__ import annotations

import re


_HANGUL = re.compile(r"[\uac00-\ud7a3]")


# Long, decision-relevant phrases are translated explicitly.  Replacements are
# applied longest-first so that complete audited notes take precedence over
# shorter UI fragments.
ENGLISH_REPLACEMENTS: dict[str, str] = {
    # Document shell and language controls.
    '<html lang="ko">': '<html lang="en">',
    '<a class="lang-switch" href="dashboard_en.html">English</a>': '<a class="lang-switch" href="dashboard.html">Korean</a>',
    'toLocaleString("ko-KR"': 'toLocaleString("en-US"',
    "한·일 철강 전환 포트폴리오 의사결정실": "Korea–Japan Steel Transition Portfolio Decision Room",
    "설비에서 이사회까지 이어지는": "From assets to the boardroom:",
    "탈탄소 자본배분 판단 화면": "a decarbonization capital-allocation decision room",
    "POSCO와 일본 3사의 공시경로에서 고정한 동일 설비 포트폴리오를 모든 시나리오에 재평가해, 경로 적합성·현금비용·탄소가치·위험을 함께 추적합니다.": "The same fixed asset portfolios derived from the disclosed pathways of POSCO and three Japanese steelmakers are re-evaluated across every scenario, linking pathway fit, cash cost, carbon value and risk.",
    "기업": "Company",
    "시나리오": "Scenario",
    "검토안": "Portfolio",
    "추천안 상세 보기": "View recommended portfolio",
    "기준 배출량": "Baseline emissions",
    "2040 잔여 배출": "2040 residual emissions",
    "P50 경제적 순비용 NPV": "P50 net economic cost NPV",
    "정렬 CAPEX": "Aligned CAPEX",
    "연간 배출 경로와 탄소예산": "Annual emissions pathway and carbon budget",
    "공시경로에서 고정한 설비·기술·전환연도를 그대로 합산합니다. 점선은 선택 시나리오 탄소예산입니다.": "Aggregates the fixed assets, technologies and transition years derived from the disclosed pathway. The dashed line is the selected scenario's carbon budget.",
    "누적 회피배출": "Cumulative avoided emissions",
    "고정 포트폴리오 배출": "Fixed-portfolio emissions",
    "시나리오 탄소예산": "Scenario carbon budget",
    "회피배출 영역": "Avoided-emissions area",
    "판단 요약": "Decision summary",
    "현재 선택안이 기업의 비용·위험·실행제약에 주는 의미": "What the selected portfolio means for cost, risk and execution constraints",
    "의사결정 효율경계": "Decision efficient frontier",
    "왼쪽·아래쪽일수록 유리합니다. 탄소예산과 스크랩·수소·계통·동시공사·실패위험 기준을 모두 충족하는 고정 포트폴리오 중 P50 비용과 TCaR을 동시에 더 낮출 수 없는 대안만 연결합니다.": "Lower and further left is better. The frontier connects only fixed portfolios that satisfy the carbon-budget, scrap, hydrogen, grid, concurrent-construction and technology-failure criteria and cannot be improved simultaneously on both P50 cost and TCaR.",
    "선택 계획": "Selected portfolio",
    "강건 후보 지도 · 동일 후보의 시나리오 이동": "Robust candidate map · same candidate across scenarios",
    "전체 조합을 현실 제약으로 선별한 뒤 회사별 대표 후보를 반복 모의합니다. 가는 선은 같은 설비·기술·연도·계약 패키지가 시나리오만 바뀔 때 이동한 방향이며, 각 색 경계는 해당 시나리오의 적격 후보 효율경계입니다.": "All combinations are screened against real-world constraints before representative candidates are simulated repeatedly by company. Thin lines show how the same asset, technology, timing and contract package moves when only the scenario changes; each colored curve is that scenario's feasible-candidate frontier.",
    "강건 기준": "Robust criterion",
    "최대후회 + λ×최악 TCaR": "Maximum regret + λ × worst-case TCaR",
    "현재 두 활성 경로는 기업 공시경로와 내부 1.5°C 스트레스입니다. 공식 GCAM 1.5°C·2.0°C 수치가 검증되기 전에는 이 강건 결과를 공식 기후경계로 해석하지 않습니다.": "The two active pathways are the corporate disclosure pathway and an internal 1.5°C stress test. Until official GCAM 1.5°C and 2.0°C values are verified, this robust result must not be interpreted as an official climate boundary.",
    "λ 추천 강건후보 · 시설과 공급여력": "λ-recommended robust candidate · assets and supply headroom",
    "결정론으로 고정한 상위 후보를 요청된 전체 경로 수로 재평가한 뒤, 현재 선택 시나리오의 시설 액션·Shapley 분산배분·연도별 스크랩·수소·증분계통 수요를 같은 화면에 연결합니다.": "Top deterministically fixed candidates are re-evaluated using the full requested path count, connecting asset actions, Shapley variance allocation and annual scrap, hydrogen and incremental-grid demand for the selected scenario.",
    "시설 블록": "Asset block",
    "기술 경로": "Technology pathway",
    "전환": "Transition",
    "순현금": "Net cash",
    "탄소가치": "Carbon value",
    "경제 NPV": "Economic NPV",
    "연간 감축": "Annual abatement",
    "연도": "Year",
    "스크랩 수요/공급": "Scrap demand / supply",
    "수소 수요/공급": "Hydrogen demand / supply",
    "계통 수요/공급": "Grid demand / supply",
    "판정": "Status",
    "자원 최대 활용률은 현재 선택 시나리오 안의 2026–2040 최댓값입니다. 기업 공급한도와 실패확률은 아직 model_estimate입니다. 아래 공식 국가 벤치마크는 단위·범위가 달라 회사 공급한도를 대체하지 않으며, 방향성과 검증 우선순위만 제공합니다.": "Maximum resource utilization is the 2026–2040 peak within the selected scenario. Company supply limits and failure probabilities remain model estimates. The official national benchmarks below differ in unit and boundary, do not replace company-level limits, and serve only as directional checks and verification priorities.",
    "설비별 전환 실행지도": "Asset-level transition execution map",
    "배출 기여도가 큰 설비부터 정렬했습니다. 비용은 기준가격 경로의 설비별 순비용 NPV이며, 기업 P50과 목적이 다릅니다.": "Assets are ordered by baseline emissions contribution. Cost is the asset-level net-cost NPV under the reference-price path and serves a different purpose from company-level P50.",
    "기준 배출": "Baseline emissions",
    "전환시점 · 2026–40": "Transition timing · 2026–40",
    "기준 NPV": "Reference NPV",
    "잔여 배출": "Residual emissions",
    "P50 경제적 순비용 브리지": "P50 net economic cost bridge",
    "실제 증분 현금비용에서 탄소비용 회피가치와 정책지원을 분리합니다. 탄소가치는 현금수익이 아닙니다.": "Separates avoided carbon-cost value and policy support from actual incremental cash cost. Carbon value is not cash revenue.",
    "단위": "Unit",
    "기본 P1–P7 TCaR 원인 · 환산 영향": "Base P1–P7 TCaR drivers · translated impact",
    "이 기본 계획 패널은 요인 단독 분산을 합계 100%로 정규화한 진단치입니다. 상관효과를 배분한 정밀 Shapley 값은 아래 강건후보 실행패널에 별도로 표시합니다.": "This base-portfolio panel normalizes standalone factor variances to 100% as a diagnostic. Refined Shapley values allocating correlation effects are shown separately in the robust-candidate execution panel.",
    "계획 비교 · 선택 근거": "Portfolio comparison · decision basis",
    "행을 누르면 설비·배출·비용 화면이 해당 계획으로 바뀝니다. P50 총액과 단위비용을 함께 봅니다.": "Select a row to update the asset, emissions and cost views. Review both total P50 and unit cost.",
    "계획": "Portfolio",
    "판단상태": "Decision status",
    "P50 총액": "P50 total",
    "단위 P50": "Unit P50",
    "정책의존": "Policy dependence",
    "경계빈도": "Frontier frequency",
    "경계 반복빈도": "Repeat-run frontier frequency",
    "공식 전환 프로젝트 증거층": "Official transition-project evidence layer",
    "회사 공시에서 확인된 용량·총사업비·지원·가동시점을 모델 입력과 분리해 보여줍니다. 총사업비의 포함범위가 달라 단순 평균으로 기술 CAPEX를 덮어쓰지 않습니다.": "Shows disclosed capacity, total project cost, support and start-up timing separately from model inputs. Because project scopes differ, disclosed costs are not averaged mechanically or used to overwrite technology CAPEX.",
    "공식 프로젝트": "Official projects",
    "프로젝트": "Project",
    "상태 / 모델 연결": "Status / model mapping",
    "용량": "Capacity",
    "총사업비": "Total project cost",
    "정부지원": "Government support",
    "가동시점": "Start-up timing",
    "공시 원단위": "Disclosed unit cost",
    "모델 원단위": "Model unit cost",
    "출처": "Source",
    "공식 기준점 · 추정치 · 검증 경계": "Official baselines · estimates · verification boundary",
    "기업 총량은 원문 링크로 추적하고, 설비 배분과 기술·가격·계약은 모델 추정으로 구분합니다.": "Company totals are traceable to primary-source links; asset allocation, technology, prices and contracts are identified as model estimates.",
    "공식 기준점": "Official baseline",
    "기업 생산량, Scope 1+2, 재무총량, 공시 감축목표를 기준점으로 사용.": "Uses company production, Scope 1+2, financial totals and disclosed reduction targets as baselines.",
    "모델 추정": "Model estimate",
    "설비 블록 배분, 재투자연도, 기술비용, 조달·지원 비율과 가격 변동 과정.": "Asset-block allocation, reinvestment years, technology costs, procurement and support shares, and price processes.",
    "비교 원칙": "Comparison principle",
    "기업 경계가 다르므로 총액은 개별 기업 판단에, 천원/tCO₂는 대안 효율 비교에 우선 사용.": "Because company boundaries differ, use totals primarily for company-specific decisions and KRW thousand/tCO₂ primarily for comparing portfolio efficiency.",
    "시나리오 출처": "Scenario provenance",
    "중요한 제한:": "Important limitations:",
    "Kobe Steel의 배출 기준은 감축목표 경계이며, 일본 3사의 재무는 연결 기준입니다. 시설별 숫자는 공시 사업장 정보를 반영한 모델 블록이지 개별 고로의 검증된 원가가 아닙니다. 현재 활성 1.5°C 스트레스는 공식 GCAM 추출값이 아닙니다. GCAM 1.5°C·2.0°C는 DB 버전과 query 감사증적이 확보될 때까지 비활성입니다.": "Kobe Steel's emissions baseline uses the reduction-target boundary, while the three Japanese companies' financials are consolidated. Asset-level figures are model blocks reflecting disclosed sites, not verified costs for individual furnaces. The active 1.5°C stress test is not an official GCAM extraction. GCAM 1.5°C and 2.0°C remain inactive until the database version, query and audit evidence are secured.",

    # Runtime decision language and chart annotations.
    "효율경계에서 P50 경제적 순비용이 가장 낮은 대안": "The portfolio with the lowest P50 net economic cost on the efficient frontier",
    "효율경계의 TCaR 중앙값 이하를 만족하는 대안 중 P50 비용이 가장 낮은 대안": "The lowest-P50 portfolio among frontier alternatives at or below the frontier's median TCaR",
    "효율경계에서 TCaR가 가장 낮은 대안": "The portfolio with the lowest TCaR on the efficient frontier",
    "비용 중심": "Cost focus",
    "균형": "Balanced",
    "안정성": "Stability focus",
    "기준 추천": "recommendation",
    "연도별 탄소예산을 충족하는 고정 포트폴리오만 대상으로 공시전략 프록시 대비 P50 NPV ": "Among fixed portfolios meeting the annual carbon budget, P50 NPV versus the disclosed-strategy proxy is ",
    "bn 절감": "bn lower",
    "bn 증가": "bn higher",
    "천원 축소": "kKRW lower",
    "천원 확대": "kKRW higher",
    "권고안은 모델 대안이며 실제 승인 전 설비별 원가 검증이 필요합니다.": "The recommendation is a model alternative; asset-level cost verification is required before approval.",
    "공식 ": "Official ",
    "설비블록 합계": "asset-block total",
    "기준 대비": "vs. baseline",
    "현금 ": "Cash ",
    "탄소회피가치 ": "avoided carbon value ",
    "현재 대비 ": "vs. current ",
    "피크 ": "Peak ",
    "개 설비": " assets",
    "기술 CAPEX": "Technology CAPEX",
    "전력": "Electricity",
    "수소": "Hydrogen",
    "공시전략 대비": "Versus disclosed strategy",
    "비용 절감 ": "Cost reduction ",
    "비용 증가 ": "Cost increase ",
    "축소 ": "lower by ",
    "확대 ": "higher by ",
    "통합 실행가능성": "Integrated feasibility",
    "탄소·자원·공사·실패기준 충족": "Meets carbon, resource, construction and failure criteria",
    "년 탄소예산 초과": " carbon-budget breach",
    "년 공급제약 초과": " supply-constraint breach",
    "공사/실패위험 기준 초과": "Construction / failure-risk criteria breached",
    "잔여 ": "Residual ",
    "예산 ": "budget ",
    "스크랩 초과 ": "scrap excess ",
    "수소 초과 ": "hydrogen excess ",
    "계통 초과 ": "grid excess ",
    "동시공사 ": "concurrent projects ",
    "실패노출 ": "failure exposure ",
    "효율성 판정": "Efficiency assessment",
    "경계 부적격": "Not frontier-eligible",
    "가 동시 개선": " improves both metrics",
    "비지배 대안": "Non-dominated alternative",
    "비용은 계산했지만 탄소예산 미충족으로 추천·효율경계에서 제외됩니다.": "Cost is calculated, but the portfolio misses the carbon budget and is excluded from recommendations and the frontier.",
    "P50과 TCaR 모두 더 낮은 적격 계획이 존재합니다.": "A feasible portfolio with both lower P50 and lower TCaR exists.",
    "적격안 중 두 판단축을 동시에 더 낮출 수 있는 계획이 없습니다.": "No feasible portfolio improves both decision axes simultaneously.",
    "동일 포트폴리오 시나리오 변화": "Same portfolio across scenarios",
    " 대비 절대 NPV ": " vs. absolute NPV ",
    "실제 순현금비용 ": "actual net cash cost ",
    "탄소회피가치 ": "avoided carbon-cost value ",
    "CAPEX·설비·연도는 동일합니다.": "CAPEX, assets and timing are unchanged.",
    "최대 양(+) 비용요인": "Largest positive cost driver",
    "실제 순현금비용과 탄소회피가치·정책지원을 분리했습니다. 경제적 순비용이 음수여도 현금수익을 뜻하지 않습니다.": "Actual net cash cost is separated from avoided carbon value and policy support. A negative net economic cost does not imply cash revenue.",
    "탄소·자원·공사·실패 제약 미충족 · 경계 제외": "Fails carbon, resource, construction or failure constraints · excluded from frontier",
    "효율경계": "Efficient frontier",
    "지배 대안 존재": "Dominated by another alternative",
    "천원/tCO₂": "kKRW/tCO₂",
    "낮은 비용 · 낮은 위험 방향": "lower cost · lower risk",
    "실행 제약 미충족": "Execution constraints not met",
    "공시전략 프록시": "Disclosed-strategy proxy",
    "효율경계 대안": "Efficient-frontier alternative",
    "지배되는 대안": "Dominated alternative",
    "P50 경제적 NPV": "P50 economic NPV",
    "공통 회피배출 분모": "Common avoided-emissions denominator",
    "이 고정 포트폴리오는 탄소예산 또는 스크랩·수소·계통·동시공사·실패위험 기준을 충족하지 못해 경계와 추천에서 제외됩니다.": "This fixed portfolio fails the carbon-budget or scrap, hydrogen, grid, concurrent-construction or failure-risk criteria and is excluded from the frontier and recommendations.",
    "는 P50을 ": " lowers P50 by ",
    "천원, TCaR을 ": "kKRW and TCaR by ",
    "천원 동시에 낮춥니다.": "kKRW simultaneously.",
    "이 대안보다 P50과 TCaR을 동시에 낮추는 비교 계획은 없습니다.": "No comparison portfolio has both lower P50 and lower TCaR.",
    "현재 위험선호의 추천은 ": "The recommendation for the current risk preference is ",
    "입니다. 위험선호가 바뀌면 효율경계 위 최적점도 바뀝니다.": ". The preferred point on the frontier changes with risk preference.",
    "경계빈도는 3개 seed에서 효율경계에 포함된 비율입니다. 100%일수록 반복 실행에 안정적입니다.": "Frontier frequency is the share of three seeds in which the portfolio lies on the efficient frontier. A value of 100% indicates stronger repeat-run stability.",
    "개 적격안": " feasible alternatives",
    "후보 결과 없음": "No candidate results",
    "후회비용": "regret cost",
    "통합 적격": "fully feasible",
    "제약 미충족": "constraints not met",
    "후보 P50": "Candidate P50",
    "후보 TCaR": "Candidate TCaR",
    "적격 경계": "feasible frontier",
    "실행제약 미충족": "execution constraints not met",
    "모든 활성 시나리오 적격": "Feasible in all active scenarios",
    "최소 위반 대안": "Least-violating alternative",
    "전체 생성": "Generated universe",
    "정밀 shortlist": "Refined shortlist",
    "강건 적격": "Robust-feasible",
    "강건 경계": "Robust frontier",
    "최대후회 P50": "Maximum P50 regret",
    "최악 TCaR": "Worst-case TCaR",
    "후회 ": "Regret ",
    "정밀 shortlist는 seed당 ": "The refined shortlist uses ",
    "경로, 반복 합계 ": " paths per seed and ",
    "경로입니다. 최대후회 기준점도 같은 shortlist 안에서 계산합니다.": " total repeated paths. The maximum-regret reference point is calculated within the same shortlist.",
    "정밀 후보 실행자료 없음": "No refined-candidate execution data",
    "정밀 시설 결과 없음": "No refined asset results",
    "정밀 P50": "Refined P50",
    "Shapley 전력/수소/건설": "Shapley electricity / hydrogen / construction",
    "스크랩": "Scrap",
    "증분계통": "Incremental grid",
    "최대 활용률": "maximum utilization",
    "최소 여유 ": "Minimum headroom ",
    "여유 내": "Within capacity",
    "초과": "Exceeded",
    "정성 정책": "Qualitative policy",
    "회사 한도 아님": "not a company limit",
    "생산": "output",
    "선택 계획 합계": "Selected-portfolio total",
    "개 블록": " blocks",
    "기준가격 NPV": "Reference-price NPV",
    "고정 OPEX": "Fixed OPEX",
    "계약 프리미엄": "Contract premium",
    "정책지원": "Policy support",
    "중앙값 보정": "Median reconciliation",
    "수소입력": "Hydrogen input",
    "건설 CAPEX": "Construction CAPEX",
    "전력 PPA": "Power PPA",
    "수소 계약": "Hydrogen contract",
    "고정 EPC": "Fixed-price EPC",
    "CCfD 적용": "CCfD coverage",
    "추천": "Recommended",
    "공시 프록시": "Disclosure proxy",
    "지배됨": "Dominated",
    "가동 중": "Operating",
    "실증 준비": "Demonstration preparation",
    "투자 결정": "Investment decision",
    "타당성 검토": "Feasibility study",
    "실증 완료": "Demonstration completed",
    "완료": "Completed",
    "신규자산·모델 미편입": "New asset · not yet modeled",
    "실증자산·모델 미편입": "Demonstration asset · not yet modeled",
    "시설·시점 앵커": "Site and timing anchor",
    "그룹자산·모델 미편입": "Group asset · not yet modeled",
    "혼합경로 증거": "Hybrid-route evidence",
    "직접 과거 앵커": "Direct historical anchor",
    "기술성능 앵커": "Technology-performance anchor",
    "건 · 기준일 ": " projects · as of ",
    "미공시": "Not disclosed",
    "원문 ↗": "Source ↗",
    "범위 해석.": "Scope interpretation.",
    "이 회사의 공시 총사업비 원단위는 ": "This company's disclosed total-project-cost range is ",
    "bn KRW/Mtpa입니다. ": "bn KRW/Mtpa. ",
    "공시 총사업비를 용량으로 나눌 수 있는 프로젝트가 아직 없습니다. ": "No disclosed project can yet be normalized by capacity. ",
    "모델 원단위는 공통 기술패키지의 스크리닝 값이고, 공시는 부두·물류·전력·후공정 또는 혼합공정을 포함할 수 있습니다. 같은 범위로 bridge하기 전에는 공시값의 단순 평균이나 직접 치환을 금지합니다.": "Model unit costs are screening values for common technology packages, while disclosures may include quays, logistics, power, downstream processes or hybrid routes. Do not average or directly substitute disclosed values until scopes are bridged consistently.",
    "2030 앵커": "2030 anchor",
    "비활성 공식 추출 슬롯": "Inactive official-extraction slots",
    "회 반복 · seeds": " repeated runs · seeds",
    "계획·시나리오당 ": " simulations per portfolio-scenario · ",
    "개 모의경로": " paths",
    "분석기간 ": "Analysis period ",
    "대표 seed ": "representative seed ",
    "시설 스케줄은 결정론적 최적화, 비용은 반복 Monte Carlo 평균": "asset schedules use deterministic optimization; costs are repeated Monte Carlo means",
    "개": " candidates",
    "조": "tn",
    "천원": "kKRW",

    # Scenario registry and audit status strings.
    "공식 기업 총량 + 명시적 모델 추정": "Official company totals + explicit model estimates",
    "기업 공시경로": "Corporate disclosure pathway",
    "내부 1.5°C 스트레스 (비-GCAM)": "Internal 1.5°C stress test (non-GCAM)",
    "GCAM 1.5°C 공식 추출 대기": "Official GCAM 1.5°C extraction pending",
    "GCAM 2.0°C 공식 추출 대기": "Official GCAM 2.0°C extraction pending",
    "기업 공시와 내부 보간": "Corporate disclosures and internal interpolation",
    "내부 스트레스 테스트": "Internal stress test",
    "한국·일본 GCAM 지역": "GCAM Korea and Japan regions",
    "기업별 원문은 companies.csv에 기록; 공시 목표를 절대배출 앵커로 환산한 경로이며 GCAM 경로가 아님": "Primary company sources are recorded in companies.csv; disclosed targets are converted into absolute-emissions anchors and do not constitute a GCAM pathway",
    "내부 가정은 METHODOLOGY.md에 기록; 1.5°C는 가속 스트레스의 방향을 뜻하며 공식 GCAM 결과가 아님": "Internal assumptions are documented in METHODOLOGY.md; 1.5°C indicates the direction of an accelerated stress test and is not an official GCAM result",
    "GCAM DB 버전·구성명·query XML·추출 CSV·SHA256이 확보되기 전에는 숫자 앵커와 정책값을 활성화하지 않음": "Numeric anchors and policy values remain inactive until the GCAM database version, configuration name, query XML, extracted CSV and SHA-256 are secured",

    # Companies, plans, assets and source-boundary notes.
    "한국": "Korea",
    "회사별 공시 경계": "Company-specific disclosure boundary",
    "POSCO 국내 사업장(포항·광양 중심)": "POSCO domestic operations (primarily Pohang and Gwangyang)",
    "Nippon Steel 일본 모회사 상공정": "Nippon Steel parent company's Japanese upstream operations",
    "JFE Steel 비연결 국내 철강사업": "JFE Steel non-consolidated domestic steel business",
    "Kobe Steel 및 주요 자회사 감축목표 경계": "Reduction-target boundary for Kobe Steel and major subsidiaries",
    "생산 34.537Mt·Scope 1+2 69.846MtCO2e는 공식값. 용량 37.4Mtpa는 모델 블록 합계. 2030/2040은 2017~2019 기준 78.8Mt의 10%/50% 감축 목표를 절대량으로 환산": "Production of 34.537 Mt and Scope 1+2 emissions of 69.846 MtCO₂e are official. Capacity of 37.4 Mtpa is the model-block total. The 2030/2040 anchors convert disclosed 10%/50% reductions from the 2017–2019 baseline of 78.8 Mt into absolute values.",
    "생산 34.30Mt·용량 38.9Mtpa·배출 72.6MtCO2는 공식값. 집약도 2.1166은 배출/생산으로 계산. 2030 절대량과 2040 중간점은 30% 감축·2050 탄소중립 공시를 반영한 모델 앵커": "Production of 34.30 Mt, capacity of 38.9 Mtpa and emissions of 72.6 MtCO₂ are official. Intensity of 2.1166 is calculated as emissions divided by production. The 2030 absolute value and 2040 midpoint are model anchors based on the disclosed 30% reduction and 2050 carbon-neutrality targets.",
    "생산 21.95Mt·Scope 1+2 45.3MtCO2·집약도 2.06은 공식값. 용량은 게이힌 중단 후 제철소 블록의 모델 합계. 목표는 2013년 58.1Mt 대비 2030년 30% 감축과 2050 탄소중립을 환산": "Production of 21.95 Mt, Scope 1+2 emissions of 45.3 MtCO₂ and intensity of 2.06 are official. Capacity is the modeled sum of works blocks after the Keihin shutdown. Targets convert the disclosed 30% reduction by 2030 from 58.1 Mt in 2013 and 2050 carbon neutrality.",
    "생산 5.96Mt는 Kobe Steel 조강(다카사고 포함), 14.3MtCO2는 감축목표 경계. 집약도는 경계가 완전히 일치하지 않아 모델 보정값. 2030은 30~40% 범위의 중간값(35%)": "Production of 5.96 Mt is Kobe Steel crude steel including Takasago; 14.3 MtCO₂ uses the reduction-target boundary. Intensity is model-adjusted because the boundaries do not fully align. The 2030 anchor uses the midpoint (35%) of the disclosed 30–40% range.",
    "POSCO 공시전략 프록시": "POSCO disclosed-strategy proxy",
    "Nippon Steel 공시전략 프록시": "Nippon Steel disclosed-strategy proxy",
    "JFE Steel 공시전략 프록시": "JFE Steel disclosed-strategy proxy",
    "Kobe Steel 공시전략 프록시": "Kobe Steel disclosed-strategy proxy",
    "광양 2.5Mt EAF·HyREX 실증 방향 반영; 계약비율은 공개부족으로 추정": "Reflects the direction of the Gwangyang 2.5 Mt EAF and HyREX demonstration; contract shares are estimated due to limited disclosure",
    "Yawata/Hirohata/Shunan EAF·다경로 기술개발 반영; 계약비율 추정": "Reflects Yawata/Hirohata/Shunan EAF and multi-pathway technology development; contract shares are estimated",
    "Kurashiki 혁신 EAF·Chiba DRI 방향과 확정 보조금 사례 반영; 계약비율 추정": "Reflects the direction of the Kurashiki innovative EAF, Chiba DRI and confirmed subsidy cases; contract shares are estimated",
    "HBI 다량장입·BF 중심 브리지 전략 반영; 장기 EAF 비중과 계약비율 추정": "Reflects a bridge strategy centered on high HBI charging and BF operations; long-term EAF share and contract shares are estimated",
    "저비용·고노출 대안": "Low-cost, high-exposure alternative",
    "지연·현물조달": "Delayed, spot-procurement",
    "균형형 라이트헤지": "Balanced, light hedging",
    "초기 계약 전환 대안": "Early contracted-transition alternative",
    "균형형 전환": "Balanced transition",
    "확실성 강화 대안": "Certainty-enhanced alternative",
    "조기 계약형 전환": "Early contracted transition",
    "완전 수소·계약형": "Full hydrogen and contracting",
    "시장위험 대부분 이전": "Transfers most market risk",
    "최대 기술·계약 확약": "Maximum technology and contract commitment",
    "지연·부분헤지": "Delayed, partial hedging",
    "중앙 대안": "Central alternative",
    "중간 기술·계약 확약": "Moderate technology and contract commitment",
    "조기 고헤지": "Early, highly hedged",
    "기존 전기로 기준 블록": "Existing EAF reference block",
    "기준 BF-BOF 복합 블록": "Reference BF–BOF integrated block",
    "기존 EAF 재생전력 업그레이드": "Existing EAF renewable-power upgrade",
    "스크랩 기반 대형 EAF": "Scrap-based large EAF",
    "수소 DRI + EAF": "Hydrogen DRI + EAF",
    "기업별 실제 집약도는 facilities.csv에서 보정": "Company-specific actual intensity is adjusted in facilities.csv",
    "기존 EAF 운영 프록시": "Existing EAF operating proxy",
    "수명연장과 에너지효율 개선의 공통 비용 프록시": "Common cost proxy for life extension and energy-efficiency improvements",
    "용해설비·전력계통·부대설비 포함 표준화 비용 가정": "Standardized cost assumption including melting equipment, grid connection and balance of plant",
    "DRI 모듈·EAF·저장·BOP 포함 표준화 비용 가정": "Standardized cost assumption including the DRI module, EAF, storage and balance of plant",
    "PPA·전력계통·효율개선 패키지 프록시": "Proxy for a PPA, grid and efficiency-improvement package",
    "POSCO 공식 국내 생산·배출 총량에 맞춘 설비 블록 배분; 개별 생산량·재투자연도는 추정": "Asset blocks allocated to match POSCO's official domestic production and emissions totals; individual output and reinvestment years are estimated",
    "Nippon Steel 공식 생산·배출·용량 총량에 맞춘 지역 블록 배분": "Regional blocks allocated to match Nippon Steel's official production, emissions and capacity totals",
    "JFE 공식 생산·배출 총량에 맞춘 설비 블록 배분": "Asset blocks allocated to match JFE's official production and emissions totals",
    "Kobe Steel 공식 조강·목표경계 배출 총량에 맞춘 블록 배분": "Blocks allocated to match Kobe Steel's official crude-steel output and target-boundary emissions totals",
    "포항제철소 BF 블록 A": "Pohang Works BF Block A",
    "포항제철소 BF 블록 B": "Pohang Works BF Block B",
    "광양제철소 BF 블록 A": "Gwangyang Works BF Block A",
    "광양제철소 BF 블록 B": "Gwangyang Works BF Block B",
    "광양 기존 EAF 블록": "Gwangyang Existing EAF Block",
    "포항": "Pohang",
    "광양": "Gwangyang",
    "East Nippon Works 블록": "East Nippon Works Block",
    "Kansai Works 블록": "Kansai Works Block",
    "Nagoya Works 블록": "Nagoya Works Block",
    "Kyushu Works Yawata 블록": "Kyushu Works Yawata Block",
    "Setouchi Works Hirohata 블록": "Setouchi Works Hirohata Block",
    "동일본": "East Nippon",
    "간사이": "Kansai",
    "나고야": "Nagoya",
    "규슈": "Kyushu",
    "세토우치": "Setouchi",
    "구라시키": "Kurashiki",
    "치바": "Chiba",
    "후쿠야마": "Fukuyama",
    "센다이": "Sendai",
    "가코가와": "Kakogawa",
    "다카사고": "Takasago",
    "Kakogawa Works BF 블록 1": "Kakogawa Works BF Block 1",
    "Kakogawa Works BF 블록 3": "Kakogawa Works BF Block 3",
    "다카사고 포함 공식 조강 총량에 맞춘 소규모 EAF 블록 추정": "Small EAF block estimated to align with official crude-steel output including Takasago",
    "2016년 BF3 개수와 장기 수명주기를 반영한 재투자연도 추정": "Reinvestment year estimated from the three BF units in 2016 and long asset life cycles",
    "공식 EAF 사업장 존재를 반영; 생산량·집약도·재투자연도 추정": "Reflects the existence of an official EAF site; output, intensity and reinvestment year are estimated",
    "2025 공식 EAF 생산 1.135Mt에 맞춘 모델 블록; 집약도·재투자연도 추정": "Model block aligned with official 2025 EAF output of 1.135 Mt; intensity and reinvestment year are estimated",
    "2028 혁신 EAF 공시를 반영한 조기 재투자 창; 생산량은 공식 총량에 맞춘 추정": "Early reinvestment window reflecting the disclosed 2028 innovative EAF; output is estimated to match the official total",
    "BF 개수·효율 패키지": "BF count and efficiency package",
    "Hirohata EAF 투자 방향을 반영한 복합 블록; 생산량·재투자연도 추정": "Composite block reflecting the Hirohata EAF investment direction; output and reinvestment year are estimated",
    "Yawata BF→EAF 공시 방향을 반영해 조기 재투자 창을 설정; 블록 생산량 추정": "Early reinvestment window reflecting the disclosed Yawata BF-to-EAF direction; block output is estimated",
}


def localize_dashboard_html(html: str) -> str:
    """Return a standalone English dashboard and fail on untranslated Hangul."""

    translated = html
    for source in sorted(ENGLISH_REPLACEMENTS, key=len, reverse=True):
        translated = translated.replace(source, ENGLISH_REPLACEMENTS[source])
    matches = list(_HANGUL.finditer(translated))
    if matches:
        contexts: list[str] = []
        for match in matches[:12]:
            start = max(0, match.start() - 45)
            end = min(len(translated), match.end() + 85)
            contexts.append(translated[start:end].replace("\n", " "))
        raise ValueError(
            "English dashboard contains untranslated Korean text: "
            + " | ".join(contexts)
        )
    return translated
