from __future__ import annotations

from .dashboard_script import DASHBOARD_SCRIPT


HTML_TEMPLATE = r'''<!doctype html>
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>한·일 철강 전환 포트폴리오 의사결정실</title>
<style>
:root{--ink:#132238;--muted:#68768a;--line:#dce3eb;--surface:#fff;--soft:#f4f7fa;--navy:#102f50;--blue:#1769aa;--teal:#0f7c7b;--green:#28866b;--amber:#b57717;--red:#a6453c;--violet:#6c58a5;--slate:#74879b;--shadow:0 10px 28px rgba(17,40,68,.07)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#eef2f6;color:var(--ink);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans KR",sans-serif;line-height:1.45}button,select{font:inherit}.shell{max-width:1440px;margin:auto;padding:18px 22px 54px}
.topbar{display:flex;align-items:center;justify-content:space-between;margin:2px 4px 14px}.brand{display:flex;align-items:center;gap:10px;font-size:12px;font-weight:800;letter-spacing:.09em}.mark{width:24px;height:24px;border-radius:7px;background:linear-gradient(145deg,var(--navy),var(--teal));box-shadow:inset 0 0 0 1px rgba(255,255,255,.2)}.top-actions{display:flex;align-items:center;gap:11px}.model-tag{color:var(--muted);font-size:11px}.lang-switch{padding:5px 9px;border:1px solid var(--line);border-radius:7px;background:#fff;color:var(--navy);font-size:10px;font-weight:800;text-decoration:none}.lang-switch:hover{border-color:#9eb0c1}
.hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:32px;align-items:end;padding:34px 38px;border-radius:22px;background:#102f50;color:#fff;box-shadow:var(--shadow);position:relative;overflow:hidden}.hero:after{content:"";position:absolute;right:-75px;top:-125px;width:360px;height:360px;border:1px solid rgba(255,255,255,.12);border-radius:50%;box-shadow:0 0 0 62px rgba(255,255,255,.025),0 0 0 124px rgba(255,255,255,.02)}.eyebrow{position:relative;z-index:1;margin:0 0 9px;color:#9ed0d2;font-size:11px;font-weight:800;letter-spacing:.14em}.hero h1{position:relative;z-index:1;margin:0;max-width:850px;font-size:clamp(28px,3.6vw,48px);line-height:1.09;letter-spacing:-.035em}.hero p{position:relative;z-index:1;max-width:880px;margin:13px 0 0;color:#d8e4ed;font-size:14px}.runmeta{position:relative;z-index:1;display:grid;gap:8px;min-width:210px}.runmeta span{padding:8px 11px;border:1px solid rgba(255,255,255,.16);border-radius:9px;background:rgba(255,255,255,.06);font-size:11px;color:#dce8ef}
.toolbar{position:sticky;top:0;z-index:20;display:flex;justify-content:space-between;gap:14px;margin:16px 0;padding:11px 12px;border:1px solid var(--line);border-radius:14px;background:rgba(255,255,255,.94);box-shadow:0 5px 20px rgba(16,47,80,.06);backdrop-filter:blur(12px)}.controls{display:flex;align-items:center;flex-wrap:wrap;gap:6px}.control-label{margin:0 4px;color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.btn{border:1px solid var(--line);border-radius:9px;padding:8px 11px;background:#fff;color:#56657a;font-size:12px;font-weight:720;cursor:pointer;transition:.15s}.btn:hover{border-color:#9eb0c1;color:var(--ink)}.btn.on{border-color:var(--navy);background:var(--navy);color:#fff}.select{min-width:235px;border:1px solid var(--line);border-radius:9px;padding:8px 32px 8px 11px;background:#fff;color:var(--ink);font-size:12px;font-weight:700}
.decision{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:18px;align-items:center;padding:20px 24px;border:1px solid #cad8e4;border-left:5px solid var(--teal);border-radius:16px;background:#fff;box-shadow:var(--shadow)}.decision-kicker{margin:0 0 4px;color:var(--teal);font-size:10px;font-weight:850;letter-spacing:.1em}.decision h2{margin:0;font-size:21px;letter-spacing:-.02em}.decision p{margin:6px 0 0;color:var(--muted);font-size:12px}.decision-actions{display:flex;justify-content:flex-end;align-items:center;gap:9px}.risk-group{display:flex;gap:4px;padding:4px;border-radius:10px;background:var(--soft)}.risk{border:0;border-radius:7px;padding:7px 10px;background:transparent;color:var(--muted);font-size:11px;font-weight:750;cursor:pointer}.risk.on{background:#fff;color:var(--navy);box-shadow:0 2px 8px rgba(16,47,80,.1)}.primary{border:0;border-radius:9px;padding:10px 13px;background:var(--teal);color:#fff;font-size:11px;font-weight:800;cursor:pointer}
.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:11px;margin-top:13px}.kpi,.panel{border:1px solid var(--line);border-radius:15px;background:var(--surface);box-shadow:0 5px 17px rgba(17,40,68,.04)}.kpi{padding:15px 16px;min-height:112px}.kpi-label{color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.03em}.kpi-value{margin-top:6px;font-size:24px;font-weight:820;letter-spacing:-.025em;font-variant-numeric:tabular-nums}.kpi-note{margin-top:4px;color:var(--muted);font-size:10.5px}.delta.good{color:var(--green)}.delta.bad{color:var(--red)}
.grid{display:grid;grid-template-columns:1.45fr .75fr;gap:13px;margin-top:13px}.panel{padding:19px;overflow:hidden}.wide{grid-column:1/-1}.panel-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;margin-bottom:12px}.panel-head h2{margin:0;font-size:16px;letter-spacing:-.01em}.panel-head p{margin:4px 0 0;color:var(--muted);font-size:11px}.head-stat{text-align:right;color:var(--muted);font-size:10px}.head-stat strong{display:block;color:var(--ink);font-size:15px}.chart{display:block;width:100%;height:auto}.legend{display:flex;flex-wrap:wrap;gap:15px;margin:4px 0 0;color:var(--muted);font-size:10px}.legend span{display:flex;align-items:center;gap:5px}.legend i{display:inline-block;width:10px;height:3px;border-radius:3px}
.logic{display:grid;gap:10px}.logic-card{padding:13px;border:1px solid var(--line);border-radius:11px;background:var(--soft)}.logic-label{color:var(--muted);font-size:9px;font-weight:850;letter-spacing:.08em}.logic-value{margin-top:4px;font-size:15px;font-weight:800}.logic-copy{margin-top:4px;color:var(--muted);font-size:10.5px}.frontier-layout{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(300px,.4fr);gap:17px}.plan-card{padding:16px;border-radius:13px;background:var(--navy);color:#fff}.plan-card .logic-label{color:#9ec6d0}.plan-card .logic-copy{color:#cbdbe6}.mini-kpis{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:13px}.mini{padding:10px;border:1px solid rgba(255,255,255,.14);border-radius:9px;background:rgba(255,255,255,.06)}.mini span{display:block;color:#bcd0dc;font-size:9px}.mini strong{font-size:15px;font-variant-numeric:tabular-nums}.status{display:inline-block;margin-top:8px;padding:3px 8px;border-radius:99px;background:#dff1ec;color:#196b57;font-size:9px;font-weight:850}.status.warn{background:#fff0dd;color:#895c16}.status.current{background:#e9edf3;color:#4c5f74}.explain{margin:12px 0 0;padding-left:17px;color:var(--muted);font-size:10.5px}.explain li{margin:6px 0}
.candidate-list{margin-top:12px;border-top:1px solid rgba(255,255,255,.14)}.candidate-row{display:grid;grid-template-columns:1fr auto;gap:9px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,.1);font-size:9.5px}.candidate-row span{color:#bcd0dc}.candidate-row strong{font-variant-numeric:tabular-nums}.robust-legend{display:flex;flex-wrap:wrap;gap:12px;margin-top:8px;color:var(--muted);font-size:9.5px}.robust-legend span{display:flex;align-items:center;gap:5px}.robust-legend i{width:9px;height:9px;border-radius:50%;display:inline-block}.robust-note{margin-top:10px;padding:9px 11px;border-radius:9px;background:var(--amber-bg);color:#76531d;font-size:9.5px}
.robust-execution{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(290px,.45fr);gap:14px}.resource-panel{display:grid;align-content:start;gap:10px}.resource-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.resource-card{padding:11px;border:1px solid var(--line);border-radius:10px;background:var(--soft)}.resource-card span,.resource-card small{display:block;color:var(--muted);font-size:9px}.resource-card strong{display:block;margin:3px 0;font-size:18px}.resource-table th,.resource-table td{padding:8px 6px;font-size:9px}
.facility-summary{display:flex;flex-wrap:wrap;gap:7px}.summary-chip{padding:5px 8px;border-radius:7px;background:var(--soft);color:var(--muted);font-size:10px}.summary-chip strong{color:var(--ink)}.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px}table{width:100%;border-collapse:collapse;font-size:11px}th,td{padding:10px 9px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}th{position:sticky;top:0;z-index:2;background:#f7f9fb;color:var(--muted);font-size:9.5px;font-weight:820;letter-spacing:.02em}th:first-child,td:first-child{text-align:left}tbody tr{cursor:pointer;transition:.12s}tbody tr:hover{background:#f6f9fb}tbody tr.selected{background:#eaf4f3}tbody tr.current{box-shadow:inset 3px 0 var(--red)}tfoot td{background:#f7f9fb;font-weight:800}
.facility-name{min-width:176px}.facility-name strong{display:block;font-size:11px}.facility-name span{color:var(--muted);font-size:9px}.tech-path{min-width:175px;text-align:left}.tech-old{color:var(--muted)}.arrow{padding:0 4px;color:var(--teal);font-weight:900}.tech-new{font-weight:750;color:var(--ink)}.em-bar{display:flex;align-items:center;gap:7px;min-width:112px}.em-track{width:58px;height:5px;border-radius:5px;background:#e6ebf0}.em-fill{height:100%;border-radius:5px;background:var(--slate)}.timeline{position:relative;width:140px;height:24px;margin:auto}.timeline:before{content:"";position:absolute;left:0;right:0;top:11px;height:2px;background:#d8e0e8}.timeline:after{content:"";position:absolute;left:var(--pos);top:6px;width:11px;height:11px;border:2px solid #fff;border-radius:50%;background:var(--teal);box-shadow:0 0 0 1px var(--teal);transform:translateX(-50%)}.timeline span{position:absolute;left:var(--pos);top:-5px;transform:translateX(-50%);font-size:8px;font-weight:800;color:var(--teal)}
.cost-layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(280px,.6fr);gap:18px}.risk-bars{display:grid;gap:14px;margin-top:12px}.risk-row{display:grid;grid-template-columns:80px 1fr 90px;align-items:center;gap:8px;font-size:10px}.risk-track{height:8px;border-radius:9px;background:#e7edf2;overflow:hidden}.risk-fill{height:100%;border-radius:9px}.risk-num{text-align:right;font-weight:750}.coverages{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:15px}.coverage{padding:9px;border:1px solid var(--line);border-radius:9px}.coverage span{display:block;color:var(--muted);font-size:9px}.coverage strong{font-size:14px}.metric-pill{display:inline-block;padding:3px 7px;border-radius:99px;background:#e8f2f2;color:#116e6d;font-size:9px;font-weight:800}.metric-pill.off{background:#eef1f4;color:#6a7787}.metric-pill.reco{background:#e8f0fb;color:#185d96}.table-plan{text-align:left}.table-plan strong{display:block}.table-plan span{color:var(--muted);font-size:9px}
.source-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.source{padding:12px;border:1px solid var(--line);border-radius:10px;background:#fafbfd}.source h3{margin:0;font-size:12px}.source p{margin:5px 0;color:var(--muted);font-size:9.5px}.source a{color:var(--blue);font-size:9.5px;text-decoration:none}.note{margin-top:10px;padding:12px 14px;border-left:4px solid var(--amber);background:#fff8e9;color:#66502a;font-size:10.5px}.method{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.method div{padding:10px;border-radius:9px;background:var(--soft);color:var(--muted);font-size:9.5px}.method strong{display:block;color:var(--ink);font-size:10px;margin-bottom:3px}footer{margin-top:16px;color:var(--muted);font-size:9.5px;text-align:center}.tip{position:fixed;z-index:50;display:none;max-width:250px;padding:8px 10px;border-radius:8px;background:#102f50;color:#fff;font-size:10px;box-shadow:var(--shadow);pointer-events:none}
@media(max-width:1050px){.hero{grid-template-columns:1fr}.runmeta{grid-template-columns:repeat(3,1fr)}.kpis{grid-template-columns:repeat(3,1fr)}.grid{grid-template-columns:1fr}.wide{grid-column:auto}.frontier-layout,.cost-layout,.robust-execution{grid-template-columns:1fr}.source-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.shell{padding:10px 8px 35px}.hero{padding:26px 20px}.runmeta{grid-template-columns:1fr}.toolbar,.decision{position:static;grid-template-columns:1fr;align-items:flex-start}.toolbar{flex-direction:column}.decision-actions{justify-content:flex-start;flex-wrap:wrap}.kpis{grid-template-columns:repeat(2,1fr)}.source-grid,.method{grid-template-columns:1fr}.resource-cards{grid-template-columns:1fr}.panel{padding:15px 10px}.select{width:100%}}@media(max-width:440px){.kpis{grid-template-columns:1fr}}
</style></head><body><main class="shell">
<div class="topbar"><div class="brand"><span class="mark"></span>CAPITAL ALLOCATION PATHWAY</div><div class="top-actions"><div class="model-tag" id="model-tag"></div><a class="lang-switch" href="dashboard_en.html">English</a></div></div>
<header class="hero"><div><div class="eyebrow">KOREA × JAPAN · STEEL TRANSITION DECISION ROOM</div><h1>설비에서 이사회까지 이어지는<br>탈탄소 자본배분 판단 화면</h1><p>POSCO와 일본 3사의 공시경로에서 고정한 동일 설비 포트폴리오를 모든 시나리오에 재평가해, 경로 적합성·현금비용·탄소가치·위험을 함께 추적합니다.</p></div><div class="runmeta"><span id="runs"></span><span id="paths"></span><span id="years"></span></div></header>
<nav class="toolbar"><div class="controls"><span class="control-label">기업</span><div class="controls" id="company-buttons"></div></div><div class="controls"><span class="control-label">시나리오</span><div class="controls" id="scenario-buttons"></div><span class="control-label">검토안</span><select class="select" id="plan-select"></select></div></nav>
<section class="decision"><div><div class="decision-kicker" id="decision-kicker"></div><h2 id="decision-title"></h2><p id="decision-copy"></p></div><div class="decision-actions"><div class="risk-group" id="risk-buttons"></div><button class="primary" id="show-recommended">추천안 상세 보기</button></div></section>
<section class="kpis"><article class="kpi"><div class="kpi-label">기준 배출량</div><div class="kpi-value" id="kpi-baseline"></div><div class="kpi-note" id="kpi-baseline-note"></div></article><article class="kpi"><div class="kpi-label">2040 잔여 배출</div><div class="kpi-value" id="kpi-residual"></div><div class="kpi-note" id="kpi-residual-note"></div></article><article class="kpi"><div class="kpi-label">P50 경제적 순비용 NPV</div><div class="kpi-value" id="kpi-cost"></div><div class="kpi-note" id="kpi-cost-note"></div></article><article class="kpi"><div class="kpi-label">TCaR · P90−P50</div><div class="kpi-value" id="kpi-tcar"></div><div class="kpi-note" id="kpi-tcar-note"></div></article><article class="kpi"><div class="kpi-label">정렬 CAPEX</div><div class="kpi-value" id="kpi-capex"></div><div class="kpi-note" id="kpi-capex-note"></div></article></section>
<div class="grid">
<section class="panel"><div class="panel-head"><div><h2>연간 배출 경로와 탄소예산</h2><p>공시경로에서 고정한 설비·기술·전환연도를 그대로 합산합니다. 점선은 선택 시나리오 탄소예산입니다.</p></div><div class="head-stat"><span>누적 회피배출</span><strong id="avoided-total"></strong></div></div><svg class="chart" id="emissions-chart" viewBox="0 0 900 390" role="img"></svg><div class="legend"><span><i style="background:#1769aa"></i>고정 포트폴리오 배출</span><span><i style="background:#b57717"></i>시나리오 탄소예산</span><span><i style="background:#d7e7ef;height:9px"></i>회피배출 영역</span></div></section>
<aside class="panel"><div class="panel-head"><div><h2>판단 요약</h2><p>현재 선택안이 기업의 비용·위험·실행제약에 주는 의미</p></div></div><div class="logic" id="logic"></div></aside>
<section class="panel wide"><div class="panel-head"><div><h2>의사결정 효율경계</h2><p>왼쪽·아래쪽일수록 유리합니다. 탄소예산과 스크랩·수소·계통·동시공사·실패위험 기준을 모두 충족하는 고정 포트폴리오 중 P50 비용과 TCaR을 동시에 더 낮출 수 없는 대안만 연결합니다.</p></div><div class="head-stat"><span>선택 계획</span><strong id="selected-plan-head"></strong></div></div><div class="frontier-layout"><svg class="chart" id="frontier-chart" viewBox="0 0 940 470" role="img"></svg><div><div class="plan-card" id="plan-card"></div><ul class="explain" id="frontier-explain"></ul></div></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>강건 후보 지도 · 동일 후보의 시나리오 이동</h2><p>전체 조합을 현실 제약으로 선별한 뒤 회사별 대표 후보를 반복 모의합니다. 가는 선은 같은 설비·기술·연도·계약 패키지가 시나리오만 바뀔 때 이동한 방향이며, 각 색 경계는 해당 시나리오의 적격 후보 효율경계입니다.</p></div><div class="head-stat"><span>강건 기준</span><strong>최대후회 + λ×최악 TCaR</strong></div></div><div class="frontier-layout"><div><svg class="chart" id="robust-chart" viewBox="0 0 940 470" role="img"></svg><div class="robust-legend" id="robust-legend"></div></div><div><div class="plan-card" id="robust-card"></div><div class="robust-note">현재 두 활성 경로는 기업 공시경로와 내부 1.5°C 스트레스입니다. 공식 GCAM 1.5°C·2.0°C 수치가 검증되기 전에는 이 강건 결과를 공식 기후경계로 해석하지 않습니다.</div></div></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>λ 추천 강건후보 · 시설과 공급여력</h2><p>결정론으로 고정한 상위 후보를 요청된 전체 경로 수로 재평가한 뒤, 현재 선택 시나리오의 시설 액션·Shapley 분산배분·연도별 스크랩·수소·증분계통 수요를 같은 화면에 연결합니다.</p></div><div class="facility-summary" id="robust-execution-summary"></div></div><div class="robust-execution"><div class="table-wrap"><table><thead><tr><th>시설 블록</th><th>기술 경로</th><th>전환</th><th>CAPEX</th><th>순현금</th><th>탄소가치</th><th>경제 NPV</th><th>연간 감축</th></tr></thead><tbody id="robust-facility-body"></tbody></table></div><div class="resource-panel"><div class="resource-cards" id="robust-resource-cards"></div><div class="table-wrap resource-table"><table><thead><tr><th>연도</th><th>스크랩 수요/공급</th><th>수소 수요/공급</th><th>계통 수요/공급</th><th>판정</th></tr></thead><tbody id="robust-resource-body"></tbody></table></div><div class="robust-note">자원 최대 활용률은 현재 선택 시나리오 안의 2026–2040 최댓값입니다. 기업 공급한도와 실패확률은 아직 model_estimate입니다. 아래 공식 국가 벤치마크는 단위·범위가 달라 회사 공급한도를 대체하지 않으며, 방향성과 검증 우선순위만 제공합니다.</div><div class="resource-cards" id="official-benchmarks"></div></div></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>설비별 전환 실행지도</h2><p>배출 기여도가 큰 설비부터 정렬했습니다. 비용은 기준가격 경로의 설비별 순비용 NPV이며, 기업 P50과 목적이 다릅니다.</p></div><div class="facility-summary" id="facility-summary"></div></div><div class="table-wrap"><table><thead><tr><th>시설 블록</th><th>기준 배출</th><th>기술 경로</th><th>전환시점 · 2026–40</th><th>정렬 CAPEX</th><th>기준 NPV</th><th>연간 감축</th><th>잔여 배출</th></tr></thead><tbody id="facility-body"></tbody><tfoot id="facility-foot"></tfoot></table></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>P50 경제적 순비용 브리지</h2><p>실제 증분 현금비용에서 탄소비용 회피가치와 정책지원을 분리합니다. 탄소가치는 현금수익이 아닙니다.</p></div><div class="head-stat"><span>단위</span><strong>KRW bn · NPV</strong></div></div><div class="cost-layout"><svg class="chart" id="waterfall-chart" viewBox="0 0 940 420" role="img"></svg><div><div class="logic-card"><div class="logic-label">기본 P1–P7 TCaR 원인 · 환산 영향</div><div class="logic-copy">이 기본 계획 패널은 요인 단독 분산을 합계 100%로 정규화한 진단치입니다. 상관효과를 배분한 정밀 Shapley 값은 아래 강건후보 실행패널에 별도로 표시합니다.</div><div class="risk-bars" id="risk-bars"></div></div><div class="coverages" id="coverages"></div></div></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>계획 비교 · 선택 근거</h2><p>행을 누르면 설비·배출·비용 화면이 해당 계획으로 바뀝니다. P50 총액과 단위비용을 함께 봅니다.</p></div><div class="head-stat"><span>Frontier</span><strong id="frontier-count"></strong></div></div><div class="table-wrap"><table><thead><tr><th>계획</th><th>판단상태</th><th>P50 총액</th><th>단위 P50</th><th>TCaR</th><th>P90 / EBITDA</th><th>정렬 CAPEX</th><th>정책의존</th><th>경계빈도</th></tr></thead><tbody id="plan-body"></tbody></table></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>공식 전환 프로젝트 증거층</h2><p>회사 공시에서 확인된 용량·총사업비·지원·가동시점을 모델 입력과 분리해 보여줍니다. 총사업비의 포함범위가 달라 단순 평균으로 기술 CAPEX를 덮어쓰지 않습니다.</p></div><div class="head-stat"><span>공식 프로젝트</span><strong id="project-count"></strong></div></div><div class="table-wrap"><table><thead><tr><th>프로젝트</th><th>상태 / 모델 연결</th><th>용량</th><th>총사업비</th><th>정부지원</th><th>가동시점</th><th>공시 원단위</th><th>모델 원단위</th><th>출처</th></tr></thead><tbody id="project-body"></tbody></table></div><div class="note" id="project-evidence-note"></div></section>
<section class="panel wide"><div class="panel-head"><div><h2>공식 기준점 · 추정치 · 검증 경계</h2><p>기업 총량은 원문 링크로 추적하고, 설비 배분과 기술·가격·계약은 모델 추정으로 구분합니다.</p></div></div><div class="source-grid" id="sources"></div><div class="method"><div><strong>공식 기준점</strong>기업 생산량, Scope 1+2, 재무총량, 공시 감축목표를 기준점으로 사용.</div><div><strong>모델 추정</strong>설비 블록 배분, 재투자연도, 기술비용, 조달·지원 비율과 가격 변동 과정.</div><div><strong>비교 원칙</strong>기업 경계가 다르므로 총액은 개별 기업 판단에, 천원/tCO₂는 대안 효율 비교에 우선 사용.</div><div id="scenario-provenance"><strong>시나리오 출처</strong></div></div><div class="note"><strong>중요한 제한:</strong> Kobe Steel의 배출 기준은 감축목표 경계이며, 일본 3사의 재무는 연결 기준입니다. 시설별 숫자는 공시 사업장 정보를 반영한 모델 블록이지 개별 고로의 검증된 원가가 아닙니다. 현재 활성 1.5°C 스트레스는 공식 GCAM 추출값이 아닙니다. GCAM 1.5°C·2.0°C는 DB 버전과 query 감사증적이 확보될 때까지 비활성입니다.</div></section>
</div><footer id="footer"></footer></main><div class="tip" id="tip"></div>
<script id="data" type="application/json">__DASHBOARD_DATA__</script><script>__DASHBOARD_SCRIPT__</script></body></html>'''

HTML_TEMPLATE = HTML_TEMPLATE.replace("__DASHBOARD_SCRIPT__", DASHBOARD_SCRIPT)
